version: "3"
  
services:
  database:
    image: "microsoft/mssql-server-linux:2017-CU1"
    ports:
      - 5100:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mySecret123
